
CREATE DATABASE retail_project;
USE retail_project;


-- CREATE TABLE -- 

Create table retail_data(	
	Customer_ID int default null,	
    Invoice bigint default null,
    StockCode int default null,
   Description varchar(500),
    InvoiceDate timestamp,
    Quantity int default null,
	Price decimal(10,2) default null,
	Total_sales decimal(10,2) default null,
    Country varchar(50)
    );

-- LOAD DATA INFILE

LOAD DATA INFILE 'path/to/retail_data.csv'
INTO TABLE retail_data
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Customer_ID, Invoice, StockCode, Description, InvoiceDate,
 Quantity, Price, Total_sales, Country);
 
 
-- USED INDEXES TO SPEED UP THE QUERIES --

Create index idx_customer ON retail_data(Customer_Id);
Create index idx_date ON retail_data(InvoiceDate);
Create index idx_invoice on retail_data(Invoice);


-- EDA
Explain Select description 
FROM retail_data;

Select * from retail_data
where customer_id is NULL or 
customer_id = "NULL";

-- Calculate percentage of bad data where price or quantity is equal to or less than 0.
Select count(price)*1.0/(Select count(*) from retail_data) as 'percentage of bad data'
from retail_data 
where quantity <= 0 
OR price <=0;

-- Explore all country from where customers comes from
Select distinct country
from retail_data;

-- Explore all description to get the idea of items they deal with.
Select distinct Description
From retail_data;

-- REVENUE ANALYSIS -- 

-- What is the total revenue generated by the company?
Select round(sum(total_sales)) as 'Total Revenue Generated'
FROM retail_data;

--  Which month generated the highest revenue?
WITH ranking as(
	Select year(invoicedate) as years,month(invoicedate) months,
	round(sum(total_sales),2) as total_revenue,
    rank() over(partition by year(invoicedate) order by round(sum(total_sales),2) desc)as rnk
	FROM retail_data
    GROUP by year(invoicedate),month(invoicedate)
)

Select years,months,total_revenue
FROM ranking
Where rnk = 1;

--  What is the month-over-month growth in revenue?
WITH growth as (
	Select year(invoicedate) as yrs,month(invoicedate) as mnth,
	SUM(total_sales) as total_revenue
	FROM retail_data
	GROUP by year(invoicedate),month(invoicedate)
),
monthly as(
	Select yrs,mnth,total_revenue,
	lag(total_revenue) over(order by yrs,mnth) as previous_rev
	FROM growth
)
Select yrs,mnth,
(total_revenue-previous_rev) as growth_monthly
FROM monthly;

--  Identify months where revenue declined compared to previous month
WITH growth as (
	Select year(invoicedate) as yrs,month(invoicedate) as mnth,
	SUM(total_sales) as total_revenue
	FROM retail_data
	GROUP by year(invoicedate),month(invoicedate)
),
monthly as(
	Select yrs,mnth,total_revenue,
	lag(total_revenue) over(order by yrs,mnth) as previous_rev
	FROM growth
)
Select yrs,mnth,
(total_revenue-previous_rev) as growth_decline_monthly
FROM monthly
where total_revenue-previous_rev < 0;

--  What percentage of total revenue comes from the top 10 customers?
WITH top_10 as (
	Select customer_id,sum(total_sales) as total_rev
	FROM retail_data 
	GROUP BY customer_id
	ORDER BY total_rev desc
	limit 10
    )
Select 
round(SUM(total_rev)*100.0/(Select sum(total_sales) from retail_data),2) as 'percentage of top 10 customers contributions'
FROM top_10 ;
-- CUSTOMER ANALYSIS

 -- Who are the top 10 customers by revenue?
WITH top_rev as(	
	Select customer_id,SUM(total_sales) as total_rev
    FROM retail_data
    group by customer_id
    ),
ranking as (
 Select customer_id,total_rev,
 rank() over(order by total_rev desc) as rnk
 from top_rev
 )
 Select customer_id,total_rev
 FROM ranking
 where rnk >= 1 and rnk <= 10;
 
--  What is the average revenue per customer?
Select customer_id,round(avg(total_sales),2) as avg_rev
FROM retail_data
group by customer_id;

--  Identify high-value customers (top 20%)
WITH revenue as(
	Select customer_id,sum(total_sales) as total_rev
	FROM retail_data
	GROUP by customer_id
),
ranked as(
Select customer_id,total_rev,
CUME_DIST() over(order by total_rev desc) as cum_dist
FROM revenue
)
Select customer_id,total_rev,cum_dist
FROM ranked 
where cum_dist <= 0.2;


--  How many customers are one-time buyers vs repeat customers?
With customers as (
	Select customer_id,
	count(*) as cnt
	from retail_data
	group by customer_id
)
Select 
CASE WHEN cnt = 1 then 'One-time Buyers' 
WHEN cnt > 1 then 'Repeat Customers'
END as Buyer_Status,count(*) as total_customers
FROM customers
GROUP by Buyer_Status;

--  What is the customer lifetime value (CLV)?
Select customer_id,sum(total_sales) as CLV
FROM retail_data
GROUP by customer_id
ORDER BY CLV desc;

-- Retention and Churn --

--  How many customers made repeat purchases?
WITH customers_count as (
	Select Customer_id
	FROM retail_data
	GROUP by Customer_id
	having count(*) > 1
)
Select count(customer_id) as total_repeat_customers
,ROUND(count(customer_id)*100.0/(Select count(distinct customer_id) from retail_data),2) as 'percentage of repeat customers'
FROM customers_count;

--  What % of customers made a repeat purchase within 30 days of their first purchase?
WITH purchases as (
	Select distinct customer_id,invoicedate,
	dense_rank() over(partition by customer_id order by invoicedate) as purchase_date
	FROM retail_data
    ),
min_date as(
Select customer_id,min(invoicedate) as first_purchase
FROM retail_data
GROUP by customer_id
having count(distinct Invoice) > 1
)

Select  count(distinct p.customer_id) as customers_within_30_days,
count(distinct p.customer_id)*100.0/(Select count(distinct customer_id) from retail_data) as '% of within30days purchase'
FROM purchases p
JOIN min_date m
on m.customer_id = p.customer_id
WHERE p.purchase_date = 2 
AND p.invoicedate <= date_add(m.first_purchase ,Interval 30 day);

--  Identify customers who haven’t purchased in the last 3 months(latest date in the dataset)
WITH dates as (
	Select max(invoicedate) as last_date
	FROM retail_data
),
customer_date as(
Select customer_id,max(invoicedate) as latest_purchase
FROM retail_data
GROUP BY customer_id
)
Select c.customer_id as 'NO purchase last 3 months'
FROM dates d
JOIN customer_date c
WHERE c.latest_purchase < date_sub(d.last_date,Interval 3 month);

--  What is the retention rate month-over-month?
WITH monthly_customers as(
	Select distinct customer_id,date_format(invoicedate,'%Y-%m-01') as dates
	FROM retail_data
),
retention as (
	Select m1.dates as dates,
    COUNT(m1.customer_id) as total_customers,
    COUNT(m2.customer_id) as retained_customers -- Customer who purchased in two consecutive month 
    FROM monthly_customers m1
    LEFT JOIN monthly_customers m2
    ON m1.customer_id = m2.customer_id
    AND m2.dates = date_add(m1.dates,Interval 1 month)
    GROUP by m1.dates
)
Select dates,total_customers,retained_customers,
ROUND((retained_customers*100.0/total_customers),2) as retention_rate
FROM retention ;

-- Product Analysis--

 -- What are the top 10 best-selling products (by quantity)?
WITH ranked as (
	 Select Description,SUM(quantity) as total_quantity,
	 dense_rank() over(order by SUM(quantity) desc) as dr
	 FROM retail_data
	 GROUP by Description
)

Select description,total_quantity
FROM ranked
WHERE dr >= 1 and dr <= 10;

--  Which products generate the highest revenue?
Select description,SUM(total_sales) as total_rev
FROM retail_data
GROUP by description
ORDER BY total_rev desc
LIMIT 1;

--  Identify products with high sales but low revenue
WITH stats AS (
    SELECT description,
	SUM(quantity) AS total_qty,
	SUM(total_sales) AS total_rev,
	NTILE(4) OVER (ORDER BY SUM(quantity) DESC) AS qty_quartile,
	NTILE(4) OVER (ORDER BY SUM(total_sales)) AS rev_quartile
    FROM retail_data
    GROUP BY description
)

SELECT description,total_qty,total_rev
FROM stats
WHERE qty_quartile = 1   -- TOP 25% QUANTITY
AND 
rev_quartile = 1; -- BOTTOM 25% REVENUE







